# Generated by Django 4.1.6 on 2023-03-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UVACourse',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=10)),
                ('catalog_number', models.IntegerField()),
                ('academic_career_description', models.CharField(max_length=50)),
                ('credits', models.SmallIntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('catalog_number', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('credits', models.SmallIntegerField()),
                ('foreign_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foreignschool')),
            ],
        ),
        migrations.CreateModel(
            name='Equivalency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foreigncourse')),
                ('uva_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uvacourse')),
            ],
        ),
    ]
