# Generated by Django 4.1.6 on 2023-03-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uvacourse',
            name='catalog_number',
            field=models.CharField(max_length=20),
        ),
    ]
