# Generated by Django 4.1.6 on 2023-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uvacourse_catalog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncourse',
            name='catalog_number',
            field=models.CharField(max_length=10),
        ),
    ]
