# Generated by Django 4.1.6 on 2023-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_foreigncourse_catalog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncourse',
            name='credits',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uvacourse',
            name='credits',
            field=models.CharField(max_length=20),
        ),
    ]
