# Generated by Django 4.1.6 on 2023-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_foreigncourse_credits_alter_uvacourse_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncourse',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uvacourse',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
