# Generated by Django 4.1.6 on 2023-03-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_equivalencyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equivalencyrequest',
            name='foreign_school',
        ),
    ]
