# Generated by Django 4.1.6 on 2023-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_equivalencyrequest_foreign_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalencyrequest',
            name='foreign_school',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
