# Generated by Django 4.1.6 on 2023-04-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
        ('app', '0009_equivalencyrequest_status'),
    ]

    operations = [
    ]
