# Generated by Django 4.1.6 on 2023-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_0006_profile_0009_equivalencyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalencyrequest',
            name='comment',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
