# Generated by Django 4.1.6 on 2023-05-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_equivalencyrequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalencyrequest',
            name='comment',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='equivalencyrequest',
            name='foreign_course_description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='equivalencyrequest',
            name='foreign_course_url',
            field=models.CharField(max_length=512),
        ),
    ]
